### ISSUE TITLE
Option to remove imported files

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css-cli#1]
Opened by @mikkotikkanen in [clean-css repo](https://github.com/jakubpawlowicz/clean-css/issues/536) - moving it here as it'll be a CLI feature.

Note that API already exposes a list of imported files under `inlinedStylesheets` field in output hash.

---

If you are running master css file which is just split with imports, it would be nice to have r.js styled removing of the imported files

Ie. if

**master.css**

``` css
@import('buttons.css')
body { background: #fff; }
```

**buttons.css**

``` css
.btn { background: #bada55; }
```

Would then become...

**master.css**

``` css
.btn { background: #bada55; }
body { background: #fff; }
```

...with `buttons.css` removed.

If file is not imported anywhere, it would be just minified as usual.
