### ISSUE TITLE
Bad interaction between mergeIntoShorthands and removeDuplicateRules

### ISSUE THREAD

**Issue by davidflanagan** [jakubpawlowicz/clean-css-cli#28]
I've got cleancss 4.2.1 running on Node 10.13.0 on MacOS

Here's my input: 

```css
body {
    border-width: 1px;
    border-style: solid;
    border-color: red;
    border-color: #123456;
}
```

If I run `cleancss -O2` on that file I get this output: `body{border:1px solid red}`

Even though the second border-color specification should override the first, it is the first that gets merged into the shorthand border property, and the output is not equivalent to the input.
